/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedShoppingRouteImport } from './routes/_protected/shopping'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedRecipesRouteImport } from './routes/_protected/recipes'
import { Route as ProtectedHouseholdCreateRouteImport } from './routes/_protected/household/create'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedShoppingRoute = ProtectedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRecipesRoute = ProtectedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHouseholdCreateRoute =
  ProtectedHouseholdCreateRouteImport.update({
    id: '/household/create',
    path: '/household/create',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes': typeof ProtectedRecipesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/shopping': typeof ProtectedShoppingRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/household/create': typeof ProtectedHouseholdCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes': typeof ProtectedRecipesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/shopping': typeof ProtectedShoppingRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/household/create': typeof ProtectedHouseholdCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/recipes': typeof ProtectedRecipesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/shopping': typeof ProtectedShoppingRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_protected/household/create': typeof ProtectedHouseholdCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes'
    | '/settings'
    | '/shopping'
    | '/login'
    | '/signup'
    | '/household/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recipes'
    | '/settings'
    | '/shopping'
    | '/login'
    | '/signup'
    | '/household/create'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/recipes'
    | '/_protected/settings'
    | '/_protected/shopping'
    | '/_public/login'
    | '/_public/signup'
    | '/_protected/household/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/shopping': {
      id: '/_protected/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ProtectedShoppingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/recipes': {
      id: '/_protected/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof ProtectedRecipesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/household/create': {
      id: '/_protected/household/create'
      path: '/household/create'
      fullPath: '/household/create'
      preLoaderRoute: typeof ProtectedHouseholdCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedRecipesRoute: typeof ProtectedRecipesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedShoppingRoute: typeof ProtectedShoppingRoute
  ProtectedHouseholdCreateRoute: typeof ProtectedHouseholdCreateRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedRecipesRoute: ProtectedRecipesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedShoppingRoute: ProtectedShoppingRoute,
  ProtectedHouseholdCreateRoute: ProtectedHouseholdCreateRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
